---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cwa
  namespace: books
  annotations:
    tailscale.com/proxy-group: private-ingress
    tailscale.com/tags: tag:k8s-private
    tailscale.com/http-redirect: "true"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - cwa
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cwa
                port:
                  name: http
