---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob-comictagger-comics.yaml
  - cronjob-comictagger-manga.yaml
  - cronjob-humble-comics.yaml
  - cronjob-humble-manga.yaml
  - cronjob-kobo.yaml
  - cronjob-manga-convert.yaml
  - helmrelease-filebrowser.yaml
  - helmrelease-kavita.yaml
  - ingress-filebrowser.yaml
  - ingress-kavita.yaml
  - namespace.yaml
  - pvcs.yaml
