---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob-kobo.yaml
  - helmrelease-kavita.yaml
  - helmrelease-mylar3.yaml
  - helmrelease-lazylibrarian.yaml
  - ingress-kavita.yaml
  - ingress-lazylibrarian.yaml
  - ingress-mylar3.yaml
  - namespace.yaml
  - pvcs.yaml
