---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob-kavita.yaml
  - helmrelease-calibre.yaml
  - helmrelease-kavita.yaml
  - ingress-calibre.yaml
  - ingress-kavita.yaml
  - namespace.yaml
  - pvcs.yaml
